CREATE TYPE "public"."modalidade" AS ENUM('ead', 'presencial', 'ambos');--> statement-breakpoint
CREATE TYPE "public"."role" AS ENUM('aluno', 'tutor');--> statement-breakpoint
CREATE TABLE "disponibilidade" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "disponibilidade_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tutor_id" text NOT NULL,
	"dia_da_semana" smallint NOT NULL,
	"start_time" text NOT NULL,
	"end_time" text NOT NULL,
	"is_ativo" boolean DEFAULT true NOT NULL,
	CONSTRAINT "dia_da_semana_check" CHECK ("disponibilidade"."dia_da_semana" >= 0 AND "disponibilidade"."dia_da_semana" <= 6)
);
--> statement-breakpoint
CREATE TABLE "endereco_atendimento" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "endereco_atendimento_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tutor_id" text NOT NULL,
	"bairro" text NOT NULL,
	"cidade" text NOT NULL,
	"estado" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "materia" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "materia_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nome" text NOT NULL,
	CONSTRAINT "materia_nome_unique" UNIQUE("nome")
);
--> statement-breakpoint
CREATE TABLE "materia_tutor" (
	"tutor_id" text NOT NULL,
	"materia_id" integer NOT NULL,
	CONSTRAINT "materia_tutor_tutor_id_materia_id_pk" PRIMARY KEY("tutor_id","materia_id")
);
--> statement-breakpoint
CREATE TABLE "nivel_ensino" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "nivel_ensino_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nome" text NOT NULL,
	CONSTRAINT "nivel_ensino_nome_unique" UNIQUE("nome")
);
--> statement-breakpoint
CREATE TABLE "nivel_ensino_tutor" (
	"tutor_id" text NOT NULL,
	"nivel_ensino_id" integer NOT NULL,
	CONSTRAINT "nivel_ensino_tutor_tutor_id_nivel_ensino_id_pk" PRIMARY KEY("tutor_id","nivel_ensino_id")
);
--> statement-breakpoint
CREATE TABLE "tutor" (
	"user_id" text PRIMARY KEY NOT NULL,
	"descricao" text,
	"modalidade" "modalidade" NOT NULL,
	"ensina_turma" boolean DEFAULT false NOT NULL,
	"ensina_privado" boolean DEFAULT true NOT NULL,
	"valor_hora" numeric(10, 2)
);
--> statement-breakpoint
CREATE TABLE "account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"telefone" text,
	"image" text,
	"role" "role" DEFAULT 'aluno' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "disponibilidade" ADD CONSTRAINT "disponibilidade_tutor_id_tutor_user_id_fk" FOREIGN KEY ("tutor_id") REFERENCES "public"."tutor"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "endereco_atendimento" ADD CONSTRAINT "endereco_atendimento_tutor_id_tutor_user_id_fk" FOREIGN KEY ("tutor_id") REFERENCES "public"."tutor"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "materia_tutor" ADD CONSTRAINT "materia_tutor_tutor_id_tutor_user_id_fk" FOREIGN KEY ("tutor_id") REFERENCES "public"."tutor"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "materia_tutor" ADD CONSTRAINT "materia_tutor_materia_id_materia_id_fk" FOREIGN KEY ("materia_id") REFERENCES "public"."materia"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nivel_ensino_tutor" ADD CONSTRAINT "nivel_ensino_tutor_tutor_id_tutor_user_id_fk" FOREIGN KEY ("tutor_id") REFERENCES "public"."tutor"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nivel_ensino_tutor" ADD CONSTRAINT "nivel_ensino_tutor_nivel_ensino_id_nivel_ensino_id_fk" FOREIGN KEY ("nivel_ensino_id") REFERENCES "public"."nivel_ensino"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tutor" ADD CONSTRAINT "tutor_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "disponibilidade_index_0" ON "disponibilidade" USING btree ("tutor_id");--> statement-breakpoint
CREATE INDEX "endereco_tutor_idx" ON "endereco_atendimento" USING btree ("tutor_id");--> statement-breakpoint
CREATE INDEX "account_userId_idx" ON "account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "session_userId_idx" ON "session" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "verification_identifier_idx" ON "verification" USING btree ("identifier");